version: '3.8'

services:
  app:
    container_name: 'Dashboard_on'
    build: 
      context: .
      dockerfile: Dockerfile
    # volumes:
    #   - .:/app
    #   - node_modules:/app/node_modules
    environment:
      - PORT=4001
    ports:
      - "9211:4001"
    # command: npm install cookie-parser && npm start
    networks:
      - backend_network

    command: ["serve", '-s', "build"]  

networks:
  backend_network:
    driver: bridge
